#!/bin/bash
# guess-renames
# Copyright (c) 2009 Colin Barrett <colin@springsandstruts.com>
#
# This software may be used and distributed according to the terms
# of the GNU General Public License, incorporated herein by reference.

export PYTHONPATH="$(dirname $(dirname $0))/testbase/lib/python:$PYTHONPATH"
export PATH="$(dirname $(dirname $0))/testbase/bin:$PATH"

pushd $(dirname $(dirname $0)) > /dev/null
mkdir -p testbase/lib/python
python setup.py install --home=testbase > /dev/null
popd > /dev/null

mkdir testdir
pushd testdir > /dev/null

echo "*** Creating repository."
svnadmin create test-repo
svn co file:///$PWD/test-repo test-wc
pushd test-wc > /dev/null
echo "*** Repository created."

(echo "alpha" && echo "bravo" && echo "charlie") > 1
(echo "delta" && echo "echo" && echo "foxtrot") > 2

echo "*** Files created. Contents:"

echo "*** 1:"
cat 1
echo "*** 2:"
cat 2

echo "*** Adding files."

svn st
svn add *
svn st
svn commit -m "Adding"

echo "*** Files added."

echo "*** Renaming."

mv 1 3
mv 2 4

echo "*** Renamed. Contents:"

echo "*** 3:"
cat 3
echo "*** 4:"
cat 4

echo "*** Guessing."

svn st
guess-renames
svn st
svn commit -m "Renaming"
svn st

echo "*** Done."

popd > /dev/null # test-wc
popd > /dev/null # test-repo
rm -rf testdir

pushd $(dirname $(dirname $0)) > /dev/null
mkdir -p testbase/lib/python
python setup.py install --home=testbase > /dev/null
popd > /dev/null

exit 0
